### ISSUE TITLE
Differenet description of datetime fields

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-email#28]
**Environment**
Jmix version: 1.0.0-SNAPSHOT

### Description of the bug
1. Install email add-on
2. Run application
3. Go to tab Administration -> Email History

**AR:**
At the right panel the following fields are used: Created at, Sending Date, Last attempt time. 
**ER:** 
field names are reduced to a single form. Example: Creation date, Sending date, Last attempt date or didn't change "Created at",  and use Sending date, Last attempt date or  Sending time, Last attempt time

**Comment by gorbunkov** [comment]
I think captions should be "Creation date, Sending date, Last attempt date"
