### ISSUE TITLE
Remove compatibility module from Email Sending

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-email#3]

**Comment by m-orlova** [comment]
**Changes:**

1. Removed SMTP properties migrated from CUBA. Now used spring boot mail properties. Mail properties can be changed in application.properties.
**Note:** property "spring.mail.host" is required to work with Spring's JavaMailSender implementation.

Available properties:
spring.mail.host (required),
spring.mail.port,
spring.mail.username,
spring.mail.password,
spring.mail.protocol (default value "smtp")
spring.mail.defaultEncoding (default UTF-8)


JavaMail properties can be specified in application.properties using prefix "spring.mail.properties". 
E.g., property "mail.smtp.connectiontimeout" should be specified in file in the following way: spring.mail.properties.mail.smtp.connectiontimeout=20000.

2. UI changes: Fields 'Cc' and 'Bcc' are added in 'Email history' and 'Resend email' screens.

3. Removed sending of multiple messages. One message is sent all recipients including Cc and Bcc.
