### ISSUE TITLE
"Access denied" after using method processQueuedEmails

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-email#30]
**Environment**
Jmix version: 1.0.0-SNAPSHOT

### Description of the bug
1. Install email add-on
2. Create new screen
3. Add button to the screen. Add Click Event containing `emailer.processQueuedEmails();`
4. Run application and click on created button 
5. Open Administration -> Email history

**ER:**
Email history opened in new tab. 
**AR:**
Appears the message "Access denied". The message does not disappear until the user re-logged in.

**Comment by Desire456** [comment]
depends on Haulmont/jmix-security#69 SystemAuthentication doesn't work correctly

**Comment by Desire456** [comment]
Can't reproduce now on Jmix version: 1.0.0-SNAPSHOT.
