### ISSUE TITLE
The attempt limit field is empty

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-email#31]
**Environment**
Jmix version: 1.0.0-SNAPSHOT

### Description of the bug
1. Install email add-on
2. Create new screen
3. Add button to the screen. Add Click Event containing `emailer.sendEmailAsync(emailInfo) ` and definition of emailInfo
4. Run application and click on created button
5. Open Administration -> Email history
6. Click on created mail

**ER:**
Field "Attempt limit" contains number equal parameter `jmix.email.defaultSendingAttemptsCount`. It makes sense to display this field only for messages with the status "Queue".
**AR:**
Field "Attempt limit" is empty and displaying for all messages

**Comment by gorbunkov** [comment]
We should fill the attemptsLimit property with the default value (if no specific value is set) when the SendingMessage entity is created. The UI component in UI, I think, should always be displayed for entities with any status.
