### ISSUE TITLE
Sorting by address field is not available

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-email#33]
**Environment:**
Jmix version: 1.0.0-SNAPSHOT
IntelliJ version: IntelliJ IDEA 2020.3.3 (Community Edition)

### Description of the bug
1. Install email add-on
2. Run application
3. Send two or more emails
4. Open Administration -> Email History
5. Click on the name of the address column

**ER:**
The emails order by "Address"
**AR:**
Sorting is not applied. No arrows are displayed next to the column name

**Comment by gorbunkov** [comment]
As I see in CUBA git history, sorting by "address" was disabled because the "address" column is of CLOB datatype, and Oracle database doesn't support sorting by CLOB - it fails with errors.
