### ISSUE TITLE
Confusing attemptsCount and attemptsMade column names in SendingMessage entity

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-email#38]
The `SendingMessage` entity contains `attemptsCount` and `attemptsMade` column.

`attemptsMade` stores a number of actual attempts number that have been made.

`attemptsCount` store a **limit** number of attempts after which the message status is changed to NOT_SENT. In UI this field is actually named *Attempts limit* that explains the meaning much better than *attempts count*.

Database column and entity property must be renamed: `attemptsCount` -> `attemptsLimit`.

The configuration property should also be renamed: `jmix.email.defaultSendingAttemptsCount` -> `jmix.email.defaultSendingAttemptsLimit`

After the issue is fixed, the documentation must also be modified: https://docs.jmix.io/jmix/0.x/email/configuration.html#jmix.email.defaultSendingAttemptsCount - the issue in [jmix-docs](https://github.com/Haulmont/jmix-docs) GitHub repository must be created.

Also, the [article about migration from CUBA](https://youtrack.haulmont.com/articles/PLAT-A-114/Migration-from-CUBA) must be updated - the liquibase changelog must rename the database column.

**Comment by dtaimanov** [comment]
@Desire456, please fix changeSet
```
<changeSet author="email" id="3" context="!cuba">
        <renameColumn tableName="EMAIL_SENDING_MESSAGE"
                      oldColumnName="ATTEMPTS_COUNT"
                      newColumnName="ATTEMPTS_LIMIT"/>
    </changeSet>
```
in `001-email.xml`: columnDatatype is [required](https://docs.liquibase.com/change-types/community/rename-column.html) for mysql and mariadb

**Comment by DartVerder** [comment]
not changed parameter in sendEmailAsync function
![count2](https://user-images.githubusercontent.com/69783839/113719088-53663980-96fe-11eb-816d-341054373eaf.png)
![count](https://user-images.githubusercontent.com/69783839/113719093-54976680-96fe-11eb-9c1c-d252cb36d201.png)

**Comment by DartVerder** [comment]
similar behaviour 
Possible changinig Emailer.java can partially solve this problem
